spring:
  datasource:
    url: "jdbc:postgresql://${APP_DB_HOST}:${APP_DB_PORT}/${APP_DB_NAME}?currentSchema=${APP_DB_SCHEMA}"
    username: ${APP_DB_USER}
    password: ${APP_DB_PASSWORD}
  liquibase:
    drop-first: true
    change-log: "classpath:/db/changelog/_main.yml"
    database-change-log-table: db_changelog
    database-change-log-lock-table: db_changelog_lock

server:
  shutdown: graceful
