spring:
  datasource:
    url: "jdbc:postgresql://${APP_DB_HOST}:${APP_DB_PORT}/${APP_DB_NAME}?currentSchema=${APP_DB_SCHEMA}"
    username: ${APP_DB_USER}
    password: ${APP_DB_PASSWORD}
  sql:
    init:
      encoding: UTF-8
      schema-locations:
        - "classpath*:org/springframework/security/oauth2/server/authorization/oauth2-authorization-schema.sql"
        - "classpath*:org/springframework/security/oauth2/server/authorization/oauth2-authorization-consent-schema.sql"
        - "classpath*:org/springframework/security/oauth2/server/authorization/client/oauth2-registered-client-schema.sql"

server:
  shutdown: graceful
