spring:
  datasource:
    url: "jdbc:postgresql://${APP_DB_HOST}:${APP_DB_PORT}/${APP_DB_NAME}?currentSchema=${APP_DB_SCHEMA}"
    username: ${APP_DB_USER}
    password: ${APP_DB_PASSWORD}
  jpa:
    show-sql: true
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  liquibase:
    drop-first: true
    change-log: "classpath:/db/changelog/_main.yml"
    database-change-log-table: db_changelog
    database-change-log-lock-table: db_changelog_lock
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${APP_PUBLIC_URL:http://localhost:${APP_PORT:8080}}"


server:
  port: ${APP_PORT:8080}
  shutdown: graceful
